import "../styles.css";
import { installPerfBridge } from "./telemetry/bridge";
import { installTelemetryDeckBridge } from "./ui/telemetryDeck";
import { installPvpRadarBridge } from "./ui/pvpRadarBridge";
import { installPvpEventBridge } from "./ui/pvpEventBridge";
import { installCombatHudBridge } from "./ui/combatHudBridge";
import { installPvpDirectorBridge } from "./ui/pvpDirectorBridge";
import { installRoundDirectorBridge } from "./ui/roundDirectorBridge";
import { installCameraDirectorBridge } from "./ui/cameraDirectorBridge";
import { installPvpDuelBridge } from "./ui/pvpDuelBridge";
import { installPvpRejectIntelBridge } from "./ui/pvpRejectIntelBridge";
import { installPublicTelemetryStripsBridge } from "./ui/publicTelemetryStripsBridge";
import { installCombatFxBridge } from "./ui/combatFxBridge";
import { installSceneTelemetryBridge } from "./ui/sceneTelemetryBridge";
import { installSceneStatusDeckBridge } from "./ui/sceneStatusDeckBridge";
import { installTokenOverviewBridge } from "./ui/tokenOverviewBridge";
import { installTokenTreasuryBridge } from "./ui/tokenTreasuryBridge";
import { installOperationsDeckBridge } from "./ui/operationsDeckBridge";
import { installAdminTreasuryBridge } from "./ui/adminTreasuryBridge";
import { installAdminAuditRuntimeBridge } from "./ui/adminAuditRuntimeBridge";
import { installAdminAssetRuntimeBridge } from "./ui/adminAssetRuntimeBridge";
import { installAdminRuntimeBridge } from "./ui/adminRuntimeBridge";
import { installAdminAssetStatusBridge } from "./ui/adminAssetStatusBridge";
import { installAdminOverviewBridge } from "./ui/adminOverviewBridge";
import { installNetSchedulerBridge } from "./net/schedulerBridge";
import { installNetApiBridge } from "./net/apiBridge";
import { installV3StateMutatorBridge } from "./game/state/v3StateBridge";
import { installAdminActionDispatchBridge } from "./core/admin/actionDispatchBridge.js";

installPerfBridge();
installTelemetryDeckBridge();
installPvpRadarBridge();
installPvpEventBridge();
installCombatHudBridge();
installPvpDirectorBridge();
installRoundDirectorBridge();
installCameraDirectorBridge();
installPvpDuelBridge();
installPvpRejectIntelBridge();
installPublicTelemetryStripsBridge();
installCombatFxBridge();
installSceneTelemetryBridge();
installSceneStatusDeckBridge();
installTokenOverviewBridge();
installTokenTreasuryBridge();
installOperationsDeckBridge();
installAdminTreasuryBridge();
installAdminAuditRuntimeBridge();
installAdminAssetRuntimeBridge();
installAdminRuntimeBridge();
installAdminAssetStatusBridge();
installAdminOverviewBridge();
installNetSchedulerBridge();
installNetApiBridge();
installV3StateMutatorBridge();
installAdminActionDispatchBridge();

// Legacy runtime stays source of truth while V3.2 TS bundle rolls out.
// @ts-ignore TS2306: legacy bootstrap file is plain script and intentionally side-effect imported.
import("../app.js").catch((err) => {
  console.error("legacy-webapp-bootstrap-failed", err);
});
